name: Verify

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  NODE_VERSION: 20.x

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish Code Metrics
        id: metrics
        uses: ./
        with:
          github_token: ${{ github.token }}
          event: ${{ toJson(github.event) }}
          excludedFileTypes: __mocks__|.test.js|Test.js|dist
          includedFileTypes: .js$

      - name: Print Result
        shell: bash
        run: cat ${{ steps.metrics.outputs.export_filename }}
